### ISSUE TITLE
Which evaluation metric is used on MultiWOZ 2.0 and MultiWOZ 2.1

### ISSUE THREAD

**Issue by dialog-dst** [google-research-datasets/dstc8-schema-guided-dialogue#35]
In the [paper](https://arxiv.org/pdf/1909.05855.pdf) provided in ReadMe, the baseline model obtains state-of-the-art joint goal accuracies of **0.516** on MultiWOZ 2.0 and **0.489** on MultiWOZ 2.1 test sets respectively, exceeding the best-known results of **0.486** and **0.456** on these datasets as reported in (Eric et al. 2019).

In the MuliWOZ dataset, the evaluation metric for joint accuracy is evaluating whether all slot values are the **exact same** with the ground truths at every turn, i.e.,  the joint accuracy is 1.0 if and only all slot values are predicted correctly, otherwise 0.

However, the evaluation metric (including **fuzzy matching score**) provided by SGD is quite different from that used on the MultiWOZ dataset. 

We are confused about which evaluation metric is used by the paper or baseline model to evaluate the MultiWOZ dataset?

**Comment by abhirast** [comment]
Thank you for the question. We didn't use fuzzy matching score while reporting results on MultiWOZ datasets. We have modified the evaluation script released at https://github.com/google-research/google-research/tree/master/schema_guided_dst so that our evaluation is same as the one used by other papers reporting results on MultiWOZ. We will clarify this in the next version of the paper.

**Comment by dialog-dst** [comment]
Thanks very much for letting us know!
