### ISSUE TITLE
Is there data base (DB) for learning the dialog policy?

### ISSUE THREAD

**Issue by ha-lins** [google-research-datasets/dstc8-schema-guided-dialogue#38]
Hi @abhirast ,

Thanks for the valuable dataset. I wonder if there is any data base (DB) for the agent to perform the dialog policy learning.  If not, could you pls tell me how the actions (including act/slot/values) are annotated? It is highly desirable to evaluate the performance of policy optimization in the SGD dataset if possible. 

Thanks.

**Comment by abhirast** [comment]
Hi @ha-lins,

Thank you for showing interest in developing policy models on our dataset. 

Each system turn consists of one or more system actions. Each system action consists of a dialogue act (all possible acts are listed in the README) with optional parameters, which could be just a slot, an intent or a slot with an associated list of values. The slot or intent comes from the schema of the service under consideration. Since the values contained in the generated action can be deterministically determined from the dialogue state, backend results or the schema, the policy module doesn't need to predict them. In the real end to end system, these values can be filled using a deterministic logic.

Also, it isn't recommended to make the policy model dependent on the database since it can change over time as new entities are added (new movies getting released) or entities are removed (tickets getting sold out). Also, many real world APIs don't expose their entire database to a dialogue system. We have provided values in the system action so that they can be used as features for dialogue state tracking or response generation modules. Hope this helps.

Thank you again for asking this question. We will post a more formal description on the README file in the next few days. Please feel free to reply here if there are any questions or concerns.

**Comment by ha-lins** [comment]
Thanks a lot!
