### ISSUE TITLE
multiwoz2.1 dataset conversion for training

### ISSUE THREAD

**Issue by yzhang123** [google-research-datasets/dstc8-schema-guided-dialogue#42]
How do you run multiwoz2.1 for schema_guided_dst since multiwoz2.1 does not have user intents and slot request actions? Do you set all slots to non-categorical slots?

**Comment by XiaoxueZang** [comment]
Hi yzhang, we only reported the joint goal accuracy on multiwoz 2.1 in our paper. We set some of the slots which have only a few number of values as categorical slots and others as non-categorial slots.

**Comment by yzhang123** [comment]
@XiaoxueZang  For training by default SGD sums up these individual losses: intent_loss, requested_slot_loss, cat_slot_status_loss, cat_slot_value_loss, noncat_slot_status_loss, span_start_loss, span_end_loss. 
a) For multiwoz do you just ignore intent_loss and requested_slot_loss? Since multiwoz does not have intents and no user requests.
b) >We set some of the slots which have only a few number of values as categorical slots and others as non-categorial slots.
What is the threshhold for the cutoff ?

**Comment by XiaoxueZang** [comment]
a) Partially correct. We ignored requested_slot_loss and used heuristics to fill in the active_intent for each turn in the data. We didn't report the active intent accuracy since it's labelled by simple heuristics. The heuristics is that if the slot values of service "A" changes between two turns, we set the active intent of the latter turn as "service A". However, from my own perspective, I think adding active_intent loss has little influence on the final performance.
b) We set the threshold as 50 that if the number of possible values of a slot is less than 50, we consider it as a categorical slot.

**Comment by yzhang123** [comment]
@XiaoxueZang Thanks alot for that information. By cleaning MultiWOZ2.1 to fit the SGD format, 10k turns had to be discarded. So instead of 113K turns i got now 103.718. Do you see the same?
If not, could you maybe share your conversion script or the converted MultiWOZ2.1 training data? Thanks!

**Comment by XiaoxueZang** [comment]
Hi yzhang123,
I just read your message. Sorry for my late reply.  
1) We don't discard dialogues and we are currently working on releasing the converted MultiWOZ 2.1. We also correct most of the annotation errors in the original dataset. The release date is planned to be around the end of April. 
2) We used all the domains in the data which is 8 in total.
Hope it answers your question.

**Comment by yzhang123** [comment]
@XiaoxueZang any updates?

**Comment by XiaoxueZang** [comment]
Thanks for your patience. I pushed the conversion script to [repo](https://github.com/google-research/google-research/tree/master/schema_guided_dst).
