### ISSUE TITLE
Release of actual database data for each schema

### ISSUE THREAD

**Issue by rayslxu** [google-research-datasets/dstc8-schema-guided-dialogue#48]
As described in the paper, a sql backend is used for the dataset with a subset of real-world values. Is there any plan to release the database? That information is useful for data synthesis approaches. 
(I can extract rows from the dialog training data, but it might not be complete. )

Thanks.

**Comment by abhirast** [comment]
Hi, thanks for your interest in the dataset. By dataset synthesis approaches, do you mean data augmentation by substituting entities in the dialogue?

By the way, we have deliberately not released the dataset tables so that models don't use them as inputs, e.g, by modeling dialogue state as a distribution over all slot values in the database. A complete databases is generally not available in real world applications either because it is too large, or not exposed by the API, or is continuously changing (e.g. new movies, songs, events etc).

**Comment by rayslxu** [comment]
Got it. Thanks.
