### ISSUE TITLE
Unclear state updates for Flight services

### ISSUE THREAD

**Issue by ygabuev** [google-research-datasets/dstc8-schema-guided-dialogue#9]
Hi!

I have found several dialogues, in which there is an unclear (moreover, inconsistent) update of slot values in the dialogue state.

1. In dialogue `train/15_00068` (service `Flights_1`), turn 5, the System offers a flight and provides values for two slots, `outbound_departure_time` and `price`. In turn 6, the user confirms, but only the slot `outbound_departure_time` gets filled in the dialogue state.

2. In dialogue `dev/1_00068` (service `Flights_3`), the same situation happens for turns 3-4. However, neither of the slots `outbound_departure_time` and `price` get filled.

It seems that it would be natural for both slots to get filled. What is the reasoning here?

**Comment by ygabuev** [comment]
@abhirast any comments?

**Comment by abhirast** [comment]
@ygabuev Thank you for pointing this out. We are looking into it and will have an update soon.

**Comment by abhirast** [comment]
Hi, thanks for your patience. We have just updated the dataset to only include those slots in the dialogue state which are listed as a required or optional slot for some intent in that service. This is because the slot_values field in the dialogue state is used to make service calls and hence other slots don't need to be tracked. Hope that answers your question. Please feel free to add any follow-ups here.
